# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fb2Akq_6E2jqlaiA8w_0c8zwzrMUROl4
"""



from google.colab import files
uploaded = files.upload()

"""Step 1: Import libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Step 2: Load the dataset"""

df = pd.")

df = pd.read_csv("archive.zip")

print(df.head())

"""Step 3: View the first 5 rows"""

print(df.head(10))

"""Step 4: View the last rows"""

df.tail()

"""Step 5: Check number of rows and columns"""

df.shape

"""Step 6: Check all column names"""

df.columns

"""Step 7: Understand the dataset"""

df.info()

"""Step 8: Statistical summary"""

df.describe()

"""Step 9: Check missing values"""

df.isnull().sum()

"""Step 10: Check duplicate rows"""

df.duplicated().sum()

"""Step 11: Check data types"""

df.dtypes

"""Step 12: Clean the price column"""

df['price'] = (
    df['price']
    .replace('[\$,]', '', regex=True)
    .astype(float)
)

df['price'].describe()

df['neighbourhood_group_cleansed'].unique()

df['property_type'].unique()

"""Step 14: Count categories"""

df['room_type'].value_counts()

df['neighbourhood_group_cleansed'].value_counts()

df['property_type'].value_counts().head(10)

"""starting the analysis of data

Question 1
Which neighbourhood has the most Airbnb listings?

Chart: Bar chart
"""

data = df['neighbourhood_group_cleansed'].value_counts()

data.plot(kind='bar')

plt.title('Airbnb Listings by Neighbourhood')
plt.xlabel('Neighbourhood')
plt.ylabel('Number of Listings')

plt.show()

"""Question 2
What percentage of listings belong to each room type?

Chart: Pie chart
"""

data = df['room_type'].value_counts()

data.plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.title('Room Type Distribution')
plt.ylabel('')

plt.show()

"""Question 3
What is the average price in each neighbourhood?

Chart: Bar chart
"""

data = df.groupby(
    'neighbourhood_group_cleansed'
)['price'].mean()

data = data.sort_values(ascending=False)

data.plot(kind='bar')

plt.title('Average Airbnb Price by Neighbourhood')
plt.xlabel('Neighbourhood')
plt.ylabel('Average Price')

plt.show()

"""Question 4
Which room type is the most expensive?

Chart: Bar chart
"""

data = df.groupby('room_type')['price'].mean()

data = data.sort_values(ascending=False)

data.plot(kind='bar')

plt.title('Average Price by Room Type')
plt.xlabel('Room Type')
plt.ylabel('Average Price')

plt.show()

"""Question 5
Is there a relationship between price and number of reviews?

Chart: Scatter plot



"""

plt.scatter(
    df['price'],
    df['number_of_reviews'],
    alpha=1.0
)

plt.title('Price vs Number of Reviews')
plt.xlabel('Price')
plt.ylabel('Number of Reviews')

plt.show()

"""Question 6
Which neighbourhood has the most reviews?

Chart: Bar chart
"""

data = df.groupby(
    'neighbourhood_group_cleansed'
)['number_of_reviews'].sum()

data = data.sort_values(ascending=False)

data.plot(kind='bar')

plt.title('Total Reviews by Neighbourhood')
plt.xlabel('Neighbourhood')
plt.ylabel('Total Reviews')

plt.show()

"""Which neighbourhood has the highest availability?

Chart: Bar chart
"""

data = df.groupby(
    'neighbourhood_group_cleansed'
)['availability_365'].mean()

data = data.sort_values(ascending=False)

data.plot(kind='bar')

plt.title('Average Availability by Neighbourhood')
plt.xlabel('Neighbourhood')
plt.ylabel('Available Days')

plt.show()

"""Question 8
What are the top 10 property types?

Chart: Horizontal bar chart
"""

data = df['property_type'].value_counts().head(10)

data.sort_values().plot(kind='barh')

plt.title('Top 10 Property Types')
plt.xlabel('Number of Listings')
plt.ylabel('Property Type')

plt.show()

"""Question 8
What are the top 10 property types?

Chart: Horizontal bar chart
"""

data = df['property_type'].value_counts().head(10)

data.sort_values().plot(kind='barh')

plt.title('Top 10 Property Types')
plt.xlabel('Number of Listings')
plt.ylabel('Property Type')

plt.show()

"""Does the number of guests affect the price?

Chart: Line chart
"""

data = df.groupby('accommodates')['price'].mean()

data.plot(
    kind='line',
    marker='o'
)

plt.title('Average Price vs Number of Guests')
plt.xlabel('Number of Guests')
plt.ylabel('Average Price')

plt.show()

"""Question 10
Which neighbourhood generates the highest estimated revenue?

Chart: Bar chart
"""

data = df.groupby(
    'neighbourhood_group_cleansed'
)['estimated_revenue_l365d'].sum()

data = data.sort_values(ascending=False)

data.plot(kind='bar')

plt.title('Estimated Revenue by Neighbourhood')
plt.xlabel('Neighbourhood')
plt.ylabel('Estimated Revenue')

plt.show()

